"""
This module provides mapping for country names to their `alpha-2` country
codes.

Examples
--------
>>> 'Singapore' -> 'SG'
... 'China' -> 'CN'
"""


import numpy as np

country_codes = {
    'AF': ['Afghanistan', 'AF', 'AFG'],
    'AX': ['Ã…land Islands', 'AX', 'ALA'],
    'AL': ['Albania', 'AL', 'ALB'],
    'DZ': ['Algeria', 'DZ', 'DZA'],
    'AS': ['American Samoa', 'AS', 'ASM'],
    'AD': ['Andorra', 'AD', 'AND'],
    'AO': ['Angola', 'AO', 'AGO'],
    'AI': ['Anguilla', 'AI', 'AIA'],
    'AQ': ['Antarctica', 'AQ', 'ATA'],
    'AG': ['Antigua and Barbuda', 'AG', 'ATG'],
    'AR': ['Argentina', 'AR', 'ARG'],
    'AM': ['Armenia', 'AM', 'ARM'],
    'AW': ['Aruba', 'AW', 'ABW'],
    'AU': ['Australia', 'AU', 'AUS'],
    'AT': ['Austria', 'AT', 'AUT'],
    'AZ': ['Azerbaijan', 'AZ', 'AZE'],
    'BS': ['Bahamas', 'BS', 'BHS'],
    'BH': ['Bahrain', 'BH', 'BHR'],
    'BD': ['Bangladesh', 'BD', 'BGD'],
    'BB': ['Barbados', 'BB', 'BRB'],
    'BY': ['Belarus', 'BY', 'BLR'],
    'BE': ['Belgium', 'BE', 'BEL'],
    'BZ': ['Belize', 'BZ', 'BLZ'],
    'BJ': ['Benin', 'BJ', 'BEN'],
    'BM': ['Bermuda', 'BM', 'BMU'],
    'BT': ['Bhutan', 'BT', 'BTN'],
    'BO': ['Bolivia (Plurinational State of)', 'BO', 'BOL', 'Bolivia, Plurinational State Of'],
    'BQ': ['Bonaire, Sint Eustatius and Saba', 'BQ', 'BES'],
    'BA': ['Bosnia and Herzegovina', 'BA', 'BIH', 'Bosnia And Herzegovina'],
    'BW': ['Botswana', 'BW', 'BWA'],
    'BV': ['Bouvet Island', 'BV', 'BVT'],
    'BR': ['Brazil', 'BR', 'BRA'],
    'IO': ['British Indian Ocean Territory', 'IO', 'IOT'],
    'BN': ['Brunei Darussalam', 'BN', 'BRN'],
    'BG': ['Bulgaria', 'BG', 'BGR'],
    'BF': ['Burkina Faso', 'BF', 'BFA'],
    'BI': ['Burundi', 'BI', 'BDI'],
    'CV': ['Cabo Verde', 'CV', 'CPV'],
    'KH': ['Cambodia', 'KH', 'KHM'],
    'CM': ['Cameroon', 'CM', 'CMR'],
    'CA': ['Canada', 'CA', 'CAN'],
    'KY': ['Cayman Islands', 'KY', 'CYM'],
    'CF': ['Central African Republic', 'CF', 'CAF'],
    'TD': ['Chad', 'TD', 'TCD'],
    'CL': ['Chile', 'CL', 'CHL'],
    'CN': ['China', 'CN', 'CHN'],
    'CX': ['Christmas Island', 'CX', 'CXR'],
    'CC': ['Cocos (Keeling) Islands', 'CC', 'CCK'],
    'CO': ['Colombia', 'CO', 'COL'],
    'KM': ['Comoros', 'KM', 'COM'],
    'CG': ['Congo', 'CG', 'COG'],
    'CD': ['Congo, Democratic Republic of the', 'CD', 'COD', 'Congo, The Democratic Republic Of The'],
    'CK': ['Cook Islands', 'CK', 'COK'],
    'CR': ['Costa Rica', 'CR', 'CRI'],
    'CI': ["CÃ´te d'Ivoire", 'CI', 'CIV'],
    'HR': ['Croatia', 'HR', 'HRV'],
    'CU': ['Cuba', 'CU', 'CUB'],
    'CW': ['CuraÃ§ao', 'CW', 'CUW'],
    'CY': ['Cyprus', 'CY', 'CYP', 'Cyphrus'],
    'CZ': ['Czechia', 'CZ', 'CZE', 'Czech Republic '],
    'DK': ['Denmark', 'DK', 'DNK'],
    'DJ': ['Djibouti', 'DJ', 'DJI'],
    'DM': ['Dominica', 'DM', 'DMA'],
    'DO': ['Dominican Republic', 'DO', 'DOM'],
    'EC': ['Ecuador', 'EC', 'ECU'],
    'EG': ['Egypt', 'EG', 'EGY'],
    'SV': ['El Salvador', 'SV', 'SLV'],
    'GQ': ['Equatorial Guinea', 'GQ', 'GNQ'],
    'ER': ['Eritrea', 'ER', 'ERI'],
    'EE': ['Estonia', 'EE', 'EST'],
    'SZ': ['Eswatini', 'SZ', 'SWZ', 'Swaziland'],
    'ET': ['Ethiopia', 'ET', 'ETH'],
    'FK': ['Falkland Islands (Malvinas)', 'FK', 'FLK'],
    'FO': ['Faroe Islands', 'FO', 'FRO'],
    'FJ': ['Fiji', 'FJ', 'FJI'],
    'FI': ['Finland', 'FI', 'FIN'],
    'FR': ['France', 'FR', 'FRA'],
    'GF': ['French Guiana', 'GF', 'GUF'],
    'PF': ['French Polynesia', 'PF', 'PYF'],
    'TF': ['French Southern Territories', 'TF', 'ATF'],
    'GA': ['Gabon', 'GA', 'GAB'],
    'GM': ['Gambia', 'GM', 'GMB'],
    'GE': ['Georgia', 'GE', 'GEO'],
    'DE': ['Germany', 'DE', 'DEU'],
    'GH': ['Ghana', 'GH', 'GHA'],
    'GI': ['Gibraltar', 'GI', 'GIB'],
    'GR': ['Greece', 'GR', 'GRC'],
    'GL': ['Greenland', 'GL', 'GRL'],
    'GD': ['Grenada', 'GD', 'GRD'],
    'GP': ['Guadeloupe', 'GP', 'GLP'],
    'GU': ['Guam', 'GU', 'GUM'],
    'GT': ['Guatemala', 'GT', 'GTM'],
    'GG': ['Guernsey', 'GG', 'GGY'],
    'GN': ['Guinea', 'GN', 'GIN'],
    'GW': ['Guinea-Bissau', 'GW', 'GNB'],
    'GY': ['Guyana', 'GY', 'GUY'],
    'HT': ['Haiti', 'HT', 'HTI'],
    'HM': ['Heard Island and McDonald Islands', 'HM', 'HMD'],
    'VA': ['Holy See', 'VA', 'VAT'],
    'HN': ['Honduras', 'HN', 'HND'],
    'HK': ['Hong Kong', 'HK', 'HKG'],
    'HU': ['Hungary', 'HU', 'HUN'],
    'IS': ['Iceland', 'IS', 'ISL'],
    'IN': ['India', 'IN', 'IND'],
    'ID': ['Indonesia', 'ID', 'IDN'],
    'IR': ['Iran (Islamic Republic of)', 'IR', 'IRN', 'Iran, Islamic Republic Of'],
    'IQ': ['Iraq', 'IQ', 'IRQ'],
    'IE': ['Ireland', 'IE', 'IRL'],
    'IM': ['Isle of Man', 'IM', 'IMN'],
    'IL': ['Israel', 'IL', 'ISR'],
    'IT': ['Italy', 'IT', 'ITA'],
    'JM': ['Jamaica', 'JM', 'JAM'],
    'JP': ['Japan', 'JP', 'JPN'],
    'JE': ['Jersey', 'JE', 'JEY'],
    'JO': ['Jordan', 'JO', 'JOR'],
    'KZ': ['Kazakhstan', 'KZ', 'KAZ'],
    'KE': ['Kenya', 'KE', 'KEN'],
    'KI': ['Kiribati', 'KI', 'KIR'],
    'KP': ["Korea (Democratic People's Republic of)", 'KP', 'PRK', 'Korea, Democratic People\'s Republic Of'],
    'KR': ['Korea, Republic of', 'KR', 'KOR' 'Republic Of Korea', 'South Korea', 'KOR', 'Republic Of Korea'],
    'KW': ['Kuwait', 'KW', 'KWT'],
    'KG': ['Kyrgyzstan', 'KG', 'KGZ'],
    'LA': ["Lao People's Democratic Republic", 'LA', 'LAO', 'Laos'],
    'LV': ['Latvia', 'LV', 'LVA'],
    'LB': ['Lebanon', 'LB', 'LBN'],
    'LS': ['Lesotho', 'LS', 'LSO'],
    'LR': ['Liberia', 'LR', 'LBR'],
    'LY': ['Libya', 'LY', 'LBY'],
    'LI': ['Liechtenstein', 'LI', 'LIE'],
    'LT': ['Lithuania', 'LT', 'LTU'],
    'LU': ['Luxembourg', 'LU', 'LUX'],
    'MO': ['Macao', 'MO', 'MAC', 'Macau'],
    'MG': ['Madagascar', 'MG', 'MDG'],
    'MW': ['Malawi', 'MW', 'MWI'],
    'MY': ['Malaysia', 'MY', 'MYS'],
    'MV': ['Maldives', 'MV', 'MDV'],
    'ML': ['Mali', 'ML', 'MLI'],
    'MT': ['Malta', 'MT', 'MLT'],
    'MH': ['Marshall Islands', 'MH', 'MHL'],
    'MQ': ['Martinique', 'MQ', 'MTQ'],
    'MR': ['Mauritania', 'MR', 'MRT'],
    'MU': ['Mauritius', 'MU', 'MUS'],
    'YT': ['Mayotte', 'YT', 'MYT'],
    'MX': ['Mexico', 'MX', 'MEX'],
    'FM': ['Micronesia (Federated States of)', 'FM', 'FSM'],
    'MD': ['Moldova, Republic of', 'MD', 'MDA', 'Moldova, Republic Of'],
    'MC': ['Monaco', 'MC', 'MCO'],
    'MN': ['Mongolia', 'MN', 'MNG'],
    'ME': ['Montenegro', 'ME', 'MNE'],
    'MS': ['Montserrat', 'MS', 'MSR'],
    'MA': ['Morocco', 'MA', 'MAR'],
    'MZ': ['Mozambique', 'MZ', 'MOZ'],
    'MM': ['Myanmar', 'MM', 'MMR'],
    'NR': ['Nauru', 'NR', 'NRU'],
    'NP': ['Nepal', 'NP', 'NPL'],
    'NL': ['Netherlands', 'NL', 'NLD'],
    'NC': ['New Caledonia', 'NC', 'NCL'],
    'NZ': ['New Zealand', 'NZ', 'NZL'],
    'NI': ['Nicaragua', 'NI', 'NIC'],
    'NE': ['Niger', 'NE', 'NER'],
    'NG': ['Nigeria', 'NG', 'NGA'],
    'NU': ['Niue', 'NU', 'NIU'],
    'NF': ['Norfolk Island', 'NF', 'NFK'],
    'MK': ['North Macedonia', 'MK', 'MKD', 'Macedonia, The Former Yugoslav Republic Of'],
    'MP': ['Northern Mariana Islands', 'MP', 'MNP'],
    'NO': ['Norway', 'NO', 'NOR'],
    'OM': ['Oman', 'OM', 'OMN'],
    'PK': ['Pakistan', 'PK', 'PAK'],
    'PW': ['Palau', 'PW', 'PLW'],
    'PS': ['Palestine, State of', 'PS', 'PSE'],
    'PA': ['Panama', 'PA', 'PAN'],
    'PG': ['Papua New Guinea', 'PG', 'PNG', 'Papua New Guinea '],
    'PY': ['Paraguay', 'PY', 'PRY'],
    'PE': ['Peru', 'PE', 'PER'],
    'PH': ['Philippines', 'PH', 'PHL'],
    'PN': ['Pitcairn', 'PN', 'PCN'],
    'PL': ['Poland', 'PL', 'POL'],
    'PT': ['Portugal', 'PT', 'PRT'],
    'PR': ['Puerto Rico', 'PR', 'PRI'],
    'QA': ['Qatar', 'QA', 'QAT'],
    'RE': ['RÃ©union', 'RE', 'REU', 'Réunion', 'Reunion Island'],
    'RO': ['Romania', 'RO', 'ROU'],
    'RU': ['Russian Federation', 'RU', 'RUS', 'Russia'],
    'RW': ['Rwanda', 'RW', 'RWA'],
    'BL': ['Saint BarthÃ©lemy', 'BL', 'BLM'],
    'SH': ['Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN'],
    'KN': ['Saint Kitts and Nevis', 'KN', 'KNA', 'Saint Kitts And Nevis'],
    'LC': ['Saint Lucia', 'LC', 'LCA'],
    'MF': ['Saint Martin (French part)', 'MF', 'MAF'],
    'PM': ['Saint Pierre and Miquelon', 'PM', 'SPM'],
    'VC': ['Saint Vincent and the Grenadines', 'VC', 'VCT'],
    'WS': ['Samoa', 'WS', 'WSM'],
    'SM': ['San Marino', 'SM', 'SMR'],
    'ST': ['Sao Tome and Principe', 'ST', 'STP'],
    'SA': ['Saudi Arabia', 'SA', 'SAU', 'Saudi Arabia '],
    'SN': ['Senegal', 'SN', 'SEN'],
    'RS': ['Serbia', 'RS', 'SRB'],
    'SC': ['Seychelles', 'SC', 'SYC'],
    'SL': ['Sierra Leone', 'SL', 'SLE'],
    'SG': ['Singapore', 'SG', 'SGP'],
    'SX': ['Sint Maarten (Dutch part)', 'SX', 'SXM', 'Sint Maarten'],
    'SK': ['Slovakia', 'SK', 'SVK'],
    'SI': ['Slovenia', 'SI', 'SVN'],
    'SB': ['Solomon Islands', 'SB', 'SLB'],
    'SO': ['Somalia', 'SO', 'SOM'],
    'ZA': ['South Africa', 'ZA', 'ZAF'],
    'GS': ['South Georgia and the South Sandwich Islands', 'GS', 'SGS'],
    'SS': ['South Sudan', 'SS', 'SSD'],
    'ES': ['Spain', 'ES', 'ESP'],
    'LK': ['Sri Lanka', 'LK', 'LKA'],
    'SD': ['Sudan', 'SD', 'SDN'],
    'SR': ['Suriname', 'SR', 'SUR'],
    'SJ': ['Svalbard and Jan Mayen', 'SJ', 'SJM'],
    'SE': ['Sweden', 'SE', 'SWE'],
    'CH': ['Switzerland', 'CH', 'CHE'],
    'SY': ['Syrian Arab Republic', 'SY', 'SYR'],
    'TW': ['Taiwan, Province of China', 'TW', 'TWN', 'Taiwan, Province Of China', 'Taiwan'],
    'TJ': ['Tajikistan', 'TJ', 'TJK'],
    'TZ': ['Tanzania, United Republic of', 'TZ', 'TZA', 'Tanzania, United Republic Of'],
    'TH': ['Thailand', 'TH', 'THA'],
    'TL': ['Timor-Leste', 'TL', 'TLS'],
    'TG': ['Togo', 'TG', 'TGO'],
    'TK': ['Tokelau', 'TK', 'TKL'],
    'TO': ['Tonga', 'TO', 'TON'],
    'TT': ['Trinidad and Tobago', 'TT', 'TTO', 'Trinidad And Tobago'],
    'TN': ['Tunisia', 'TN', 'TUN'],
    'TR': ['Turkey', 'TR', 'TUR'],
    'TM': ['Turkmenistan', 'TM', 'TKM'],
    'TC': ['Turks and Caicos Islands', 'TC', 'TCA'],
    'TV': ['Tuvalu', 'TV', 'TUV'],
    'UG': ['Uganda', 'UG', 'UGA'],
    'UA': ['Ukraine', 'UA', 'UKR'],
    'AE': ['United Arab Emirates', 'AE', 'ARE'],
    'GB': ['United Kingdom of Great Britain and Northern Ireland', 'GB', 'GBR', 'United Kingdom (CITIZEN)', 'United Kingdom'],
    'US': ['United States of America', 'US', 'USA', 'United States'],
    'UM': ['United States Minor Outlying Islands', 'UM', 'UMI'],
    'UY': ['Uruguay', 'UY', 'URY'],
    'UZ': ['Uzbekistan', 'UZ', 'UZB'],
    'VU': ['Vanuatu', 'VU', 'VUT'],
    'VE': ['Venezuela (Bolivarian Republic of)', 'VE', 'VEN', 'Venezuela, Bolivarian Republic Of'],
    'VN': ['Viet Nam', 'VN', 'VNM', 'Vietnam'],
    'VG': ['Virgin Islands (British)', 'VG', 'VGB', 'Virgin Islands, British'],
    'VI': ['Virgin Islands (U.S.)', 'VI', 'VIR'],
    'WF': ['Wallis and Futuna', 'WF', 'WLF'],
    'EH': ['Western Sahara', 'EH', 'ESH'],
    'YE': ['Yemen', 'YE', 'YEM'],
    'ZM': ['Zambia', 'ZM', 'ZMB'],
    'ZW': ['Zimbabwe', 'ZW', 'ZWE'],
    'NA': ['Namibia', 'NA', 'NAM'],
    'XA': ['Canary Islands', 'XA', 'xa'],
    None: ['.', None, np.nan]
}